# Generated by Django 5.2.8 on 2025-11-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('announcements', 'Announcements'), ('events', 'Events'), ('achievements', 'Achievements'), ('academics', 'Academics'), ('others', 'Others')], default='announcements', max_length=20),
        ),
    ]
